### ISSUE TITLE
AVS Workbook - Terms of service warning"

### ISSUE THREAD

**Issue by suellenferreira** [Azure/Enterprise-Scale-for-AVS#160]
During the "Review and Create" page it gives a red warning saying, "You will need to Agree to the terms of service below to create this resource successfully.". But there is no option to really accept the term. Customer just need to move forward and execute the template. It can cause confusion.

**Comment by prasad3017** [comment]
@shaunjacob  @ScottHolden  - I have this for couple of customers. Could you please check on this?

**Comment by prasad3017** [comment]
@Mahesh-MSFT  Looking to see if you can help to resolve this issue?

**Comment by prasad3017** [comment]
@sonmitt  checking to see if you can help to fix this with help of @ScottHolden

**Comment by prasad3017** [comment]
@sonmitt  this is fixed. Could you please cross check and close the issue?

**Comment by sonmitt** [comment]
Just verified. I am still facing it. Checking with other users.
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/71252948/205357942-e6c4c70c-b6a3-4bb7-87b4-3a70a64eae99.png">

**Comment by sonmitt** [comment]
@prasad3017 @shaunjacob 
I verified deploying the Workbook today. Though it is working fine and deployed successfully. The warning banner still persists. 

<img width="739" alt="image" src="https://user-images.githubusercontent.com/71252948/205983050-2ff98587-2bb8-4b62-99fe-9ac50cdc2756.png">

**Comment by sonmitt** [comment]
No such warning with custom template deployment. Not able to figure out from where this error is coming when deploying with "Deploy to Azure" button.
Reached out to Scott Holden to check with him.

**Comment by jchancellor-ms** [comment]
@prasad3017 and @sonmitt - can you confirm this error is no longer happening.  I was working with support and it now seems to be working.  Interestingly, I only saw this on the AVS Field subscription and not my personal test subscription so it may have been limited to a configuration issue on the Field subscription.

**Comment by sblair01** [comment]
![image](https://user-images.githubusercontent.com/6500757/210401964-a7ebfddb-0005-4a88-b649-5628b1669917.png)

**Comment by sonmitt** [comment]
@jchancellor-ms 
I still see the warning banner for AVS Field and CSU subscription but not with my personal subscription.
Seems like a bug.

**Comment by sonmitt** [comment]
@prasad3017  
Issue is resolved now. Tested with both AVS Field sub and CSU sub, validation is passed without any warning.

@jchancellor-ms @sblair01 Would you like to verify from your end before we close this Issue in github?

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/71252948/212809338-d56cf799-698c-4cbd-971f-d0f91edf7638.png">

**Comment by jchancellor-ms** [comment]
I believe we can close this.  Got a response from support last night where they indicate that this appears to be a specific issue with the special offer type associated with the GBB subscription.  I don't expect customers to see this issue.

Jon
________________________________

**Comment by sblair01** [comment]
Syncing with the requester @suellenferreira and will close this out once I get sign off.
